spring.application.name=desafio-votos

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/desafio_votos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}

integracao.cpf.habilitada=${INTEGRACAO_CPF_HABILITADA:false}
integracao.cpf.url-base=${INTEGRACAO_CPF_URL_BASE:https://user-info.herokuapp.com/users}
integracao.cpf.timeout-segundos=${INTEGRACAO_CPF_TIMEOUT_SEGUNDOS:3}

app.base-url=${APP_BASE_URL:http://localhost:8080}
